"""add_weight_unit_to_pets

Revision ID: 33af8a3e7f3d
Revises: da3477ec31f2
Create Date: 2025-07-15 21:26:38.237672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33af8a3e7f3d'
down_revision: Union[str, Sequence[str], None] = 'da3477ec31f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('weight_unit', sa.String(), nullable=False, server_default='kg'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'weight_unit')
    # ### end Alembic commands ###
