"""deleting-temperature

Revision ID: 7356beaf9de1
Revises: 82c129becd67
Create Date: 2025-06-30 10:19:52.095101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7356beaf9de1'
down_revision: Union[str, Sequence[str], None] = '82c129becd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Remove temperature and weight fields from activity_records table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_records', 'temperature')
    op.drop_column('activity_records', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Re-add temperature and weight fields to activity_records table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_records', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('activity_records', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###
