"""add_cascade-deletion

Revision ID: 7e79a18a7ef5
Revises: 0ed7ca08e44f
Create Date: 2025-06-28 19:14:34.071325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e79a18a7ef5'
down_revision: Union[str, Sequence[str], None] = '0ed7ca08e44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only update the foreign key constraint to add cascade deletion
    op.drop_constraint(op.f('activity_records_pet_id_fkey'), 'activity_records', type_='foreignkey')
    op.create_foreign_key(None, 'activity_records', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only revert the foreign key constraint change
    op.drop_constraint(None, 'activity_records', type_='foreignkey')
    op.create_foreign_key(op.f('activity_records_pet_id_fkey'), 'activity_records', 'pets', ['pet_id'], ['id'])
    # ### end Alembic commands ###
