"""add-new-fields

Revision ID: 82c129becd67
Revises: a1b2c3d4e5f6
Create Date: 2025-06-30 06:12:29.949217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82c129becd67'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_records', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('activity_records', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('activity_records', sa.Column('weight', sa.Float(), nullable=True))
    op.alter_column('activity_records', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_records', 'quantity',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('activity_records', 'weight')
    op.drop_column('activity_records', 'temperature')
    op.drop_column('activity_records', 'duration')
    # Removed table recreation commands since we're not dropping them
    # ### end Alembic commands ###
