"""add_notify_field

Revision ID: a1b2c3d4e5f6
Revises: 7e79a18a7ef5
Create Date: 2025-06-30 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '7e79a18a7ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add notify field to activity_records table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_records', sa.Column('notify', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove notify field from activity_records table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_records', 'notify')
    # ### end Alembic commands ### 