"""fix enum

Revision ID: da3477ec31f2
Revises: 687d077b9911
Create Date: 2025-07-14 12:27:23.986439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da3477ec31f2'
down_revision: Union[str, Sequence[str], None] = '687d077b9911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем новые ENUM типы
    activity_category_enum = sa.Enum('FEEDING', 'CARE', 'ACTIVITY', name='activity_category_enum')
    activity_category_enum.create(op.get_bind(), checkfirst=True)
    
    repeat_type_enum = sa.Enum('NONE', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='repeat_type_enum')
    repeat_type_enum.create(op.get_bind(), checkfirst=True)
    
    # Обновляем колонки activity_records
    op.execute("ALTER TABLE activity_records ALTER COLUMN category TYPE activity_category_enum USING category::text::activity_category_enum")
    op.execute("ALTER TABLE activity_records ALTER COLUMN repeat_type TYPE repeat_type_enum USING repeat_type::text::repeat_type_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем старые ENUM типы
    op.execute("ALTER TABLE activity_records ALTER COLUMN repeat_type TYPE repeattype USING repeat_type::text::repeattype")
    op.execute("ALTER TABLE activity_records ALTER COLUMN category TYPE activitycategory USING category::text::activitycategory")
    
    # Удаляем новые ENUM типы
    repeat_type_enum = sa.Enum('NONE', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='repeat_type_enum')
    repeat_type_enum.drop(op.get_bind(), checkfirst=True)
    
    activity_category_enum = sa.Enum('FEEDING', 'CARE', 'ACTIVITY', name='activity_category_enum')
    activity_category_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
